language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dharma' ]; then cd .. && eval "mv $currentfolder generator-dharma" && cd generator-dharma; fi

